version: "3.8"

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: daesoo94
      MYSQL_PASSWORD: vndtkstla2
      MYSQL_DATABASE: strapi
    volumes:
      - mysql_volumes:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - strapi
    volumes:
      - ./.compose/nginx/nginx.conf:/etc/nginx/nginx.conf

  strapi:
    build:
      context: .
      dockerfile: ./.compose/strapi/dockerfile
    ports:
      - 1337:1337
    command: sh /start.sh
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=daesoo94
      - DATABASE_PASSWORD=vndtkstla2
      - BASE_URL=http://localhost
    depends_on:
      - mysql
    volumes:
      - ./strapi/:/home/service/strapi/
      - strapi_node_modules:/home/service/strapi/node_modules/

volumes:
  mysql_volumes:
  strapi_node_modules: